"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('network', sa.Enum('solana', 'aptos', name='network'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('addresses', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tg_subscribers',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('spread_threshold', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('above_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solana_address', sa.String(length=64), nullable=True),
    sa.Column('aptos_address', sa.String(length=80), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('source_protocol', sa.String(length=64), nullable=True),
    sa.Column('dest_protocol', sa.String(length=64), nullable=True),
    sa.Column('amount_usdc', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('created', 'withdrawn', 'burned', 'attested', 'minted', 'deposited', 'minted_no_deposit', 'failed', name='transferstatus'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('burn_tx_hash', sa.String(length=100), nullable=True),
    sa.Column('mint_tx_hash', sa.String(length=100), nullable=True),
    sa.Column('deposit_tx_hash', sa.String(length=100), nullable=True),
    sa.Column('cctp_message', sa.String(), nullable=True),
    sa.Column('cctp_attestation', sa.String(), nullable=True),
    sa.Column('cctp_nonce', sa.String(length=80), nullable=True),
    sa.Column('fees', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_aptos_address'), 'transfers', ['aptos_address'], unique=False)
    op.create_index(op.f('ix_transfers_reference'), 'transfers', ['reference'], unique=False)
    op.create_index(op.f('ix_transfers_solana_address'), 'transfers', ['solana_address'], unique=False)
    op.create_index(op.f('ix_transfers_status'), 'transfers', ['status'], unique=False)
    op.create_table('rate_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('apy_base', sa.Float(), nullable=True),
    sa.Column('apy_rewards', sa.Float(), nullable=True),
    sa.Column('tvl', sa.Float(), nullable=True),
    sa.Column('utilization', sa.Float(), nullable=True),
    sa.Column('available_liquidity', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('diverged', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_snapshots_protocol_id'), 'rate_snapshots', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_rate_snapshots_ts'), 'rate_snapshots', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_snapshots_ts'), table_name='rate_snapshots')
    op.drop_index(op.f('ix_rate_snapshots_protocol_id'), table_name='rate_snapshots')
    op.drop_table('rate_snapshots')
    op.drop_index(op.f('ix_transfers_status'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_solana_address'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_reference'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_aptos_address'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_table('tg_subscribers')
    op.drop_table('protocols')
    # ### end Alembic commands ###
